indumentariaonline/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("shop/", include("shop.urls")),
    path("admin/", admin.site.urls)
]

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("index", views.index, name="index"),
    path("contacto", views.contacto, name="contacto"),
    path("nueva_remera", views.nueva_remera, name="nueva_remera"),
    path("modificar_indumentaria/<int:pk>", views.modificar_indumentaria, name="modificar_indumentaria"),
    path("eliminar_indumentaria/<int:pk>", views.eliminar_indumentaria, name="eliminar_indumentaria")
]

shop/models.py
from django.db import models


class Remera(models.Model):
    marca = models.CharField("Marca", max_length=128)
    TALLES = (
        (1, "XS"),
        (2, "S"),
        (3, "M"),
        (4, "L"),
        (5, "XL"),
        (6, "XXL")
    )
    talle = models.PositiveSmallIntegerField("Talle", choices=TALLES)
    color = models.CharField("Color", max_length=128)
    lisa = models.BooleanField("Lisa")
    GENEROS = (
        (1, "Hombre"),
        (2, "Mujer"),
        (3, "Unisex")
    )
    genero = models.PositiveSmallIntegerField("Género", choices=GENEROS)

    def __str__(self):
        return f"{self.marca} {self.color} {self.get_talle_display()}"

shop/forms.py
from django.forms import ModelForm
from shop.models import Remera

class RemeraForm(ModelForm):
    class Meta:
        model= Remera
        fields = '__all__'

shop/views.py
from django.shortcuts import render, redirect
from .models import Remera
from .forms import RemeraForm
from django.contrib import messages


def index(request):
    remeras = Remera.objects.all()
    messages.success(request, "¡Indumentaria listados!")
    datos = {"remeras": remeras}
    return render(request, "shop/index.html", datos)


def contacto(request):
    return render(request, "shop/contacto.html")

def nueva_remera(request, template_name='shop/nueva_remera.html'):
    if request.method == 'POST':
        form = RemeraForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request, "¡Indumentaria registrada!")
            return redirect("index")
    else:
        form = RemeraForm()
    dato = {
        'form': form
    }
    return render(request, template_name, dato)

def modificar_indumentaria(request, pk, template_name='shop/nueva_remera.html'):
    remera = Remera.objects.get(id=pk)
    form = RemeraForm(request.POST or None, instance=remera)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=True)
            messages.success(request, "¡Indumentaria actualizada!")
            return redirect('index')
    datos = {
        "form": form
    }
    return render(request, template_name, datos)

def eliminar_indumentaria(request, pk):
    remera = Remera.objects.get(id=pk)
    remera.delete()
    messages.success(request, "¡Indumentaria eliminada!")
    return redirect('index')

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
        
    {% endblock %} - Indumentaria Online
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'shop/logo.png' %}" alt="">
                </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>   
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active text-danger" aria-current="page" href="{% url 'index' %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-danger" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Indumentaria
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'nueva_remera' %}">Nueva Remera</a></li>
                            <li><a class="dropdown-item" href="{% url 'contacto' %}">Contacto</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="contenido-main">
            {% block content %}

            {% endblock %}
        </div>
    </main>
    <footer>
        <div class="contenedor-footer">
            <p class="m-auto text-danger fw-bold">
                &copy; Proyecto indumentaria online 2022 
            </p>
        </div>
    </footer>
</body>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</html>

shop/templates/shop/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Contacto
{% endblock %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% block content %}
    <div class="text bg-danger contenedor-titulo-contacto">
        <h1 class="titulo-contacto">Contacto</h1>
    </div>
    <div class="d-flex justify-content-center align-items-center contenedor-contacto">
        <div class="contenedor-img-contacto">
            <img src="{% static 'shop/logo.png' %}" alt="logo-indumentaria">
        </div>
        <div>
            <p>
                <i class="fa-solid fa-location-dot text-danger"></i><span> Direccion</span>: Av. Le Vayer 1234
            </p>
            <p>
                <i class="fa-brands fa-square-whatsapp text-danger"></i><span> Teléfono</span>: +541156714322
            </p>
            <p>
                <i class="fa-solid fa-envelope text-danger"></i><span> Email</span>: contacto@indumentaria-online.com
            </p>
        </div>
    </div>
{% endblock %}

shop/templates/shop/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Inicio
{% endblock %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<h1 class="text-center fw-bold bg-danger">¡Bienvenido a nuestro sitio de gestion de indumentaria!</h1>
<div class="text fw-bold bg-danger contenedor-titulo-catalogo">
    <h3>Catálogo de Indumentarias</h3>
</div>
<div class="container text-center p-sm-5">
    <table class="table table-dark table-bordered border-danger">
        <thead>
            <tr>
                <th>#</th>
                <th>Marca</th>
                <th>Talle</th>
                <th>Color</th>
                <th>Lisa</th>
                <th>Género</th>
                <th>Editar</th>
                <th>Borrar</th>
            </tr>
        </thead>
    {% for remera in remeras %}
        <tbody class="table-group-divider">
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ remera.marca }}</td>
                <td>{{ remera.get_talle_display }}</td>
                <td>{{ remera.color }}</td>
                <td>
                    {% if remera.lisa %}
                        Sí
                    {% else %}
                        No
                    {% endif %}
                </td>
                <td>{{ remera.get_genero_display }}</td>
                <td><a href="{% url 'modificar_indumentaria' remera.id %}"><img src="{% static 'shop/editar_25.png' %}" alt="editar"></a></td>
                <td><a href="{% url 'eliminar_indumentaria' remera.id %}" class="link-eliminacion"><img src="{% static 'shop/eliminar_25.png' %}" alt="eliminar"></a></td>
            </tr>
    {% endfor %}
        </tbody>
    </table>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

shop/templates/shop/nueva_remera.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Nueva remera
{% endblock %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
{% block content %}
    <div class="text bg-danger contenedor-titulo-nueva-remera">
        <h1 class="titulo-nueva-remera">Nueva Remera</h1>
    </div>
    <div class="d-flex justify-content-center contenedor-formulario">
        <form class="form-control-lg p-lg-5 formulario" method="post">{% csrf_token %}
            {{ form.as_p }}
            <div class="text-center mt-5">
                <button type="submit" class="btn btn-danger">Guardar</button>
            </div>
        </form>
    </div>
{% endblock %}